def ventas_bienvenida():
    print("********************************************")
    print("Bienvenido a la tienda claro ")
    print("Tecnologia")
    print("1.audifonos")
    print("2.Televisores")
    print("3.computadores")
    print("********************************************")
    print("Celulares")
    print("4.apple")
    print("5.Samsumg")
    print("6.Motorola")
    print("7.Xiaomi")
    print("8.Tecno")
    
    print("********************************************")   